### ISSUE TITLE
Clarification/Enhancement

### ISSUE THREAD

**Issue by matthewbahr** [ojroques/vim-oscyank#1]
Just a suggestion: 

You could add this to your readme as an example of how to automatically perform a OSC52 yank whenever you yank text with y:

```
augroup YankOSC52
    autocmd!
    autocmd TextYankPost * if v:event.operator ==# 'y' | :call YankOSC52(getreg('"')) | endif
augroup END
```

**Comment by ojroques** [comment]
Good suggestion thanks! I've extended it a bit so that the command is not executed when we yank to another register.
