### ISSUE TITLE
Thank you!!

### ISSUE THREAD

**Issue by sbromberger** [ojroques/vim-oscyank#12]
Just found this plugin - it's amazingly useful. Thanks for making it.

Just FYI (and maybe to include in the "working configs" dataset), my setup is:

iPad pro using Blink -> mosh to remote host -> tmux -> neovim master

My relevant config looks like this:

```
local autocmds = {
	textyank = {
		{'TextYankPost', '*', 'silent! lua vim.highlight.on_yank({timeout=250})'},
		{'TextYankPost', '*', 'if v:event.operator is "y" && v:event.regname is "" | OSCYankReg " | endif'}
	};
}
```

Thanks again. This plugin made my day.

**Comment by ojroques** [comment]
Thank you I'm glad you appreciate the plugin :) I'll make sure to point people to this issue if they share a setup similar to yours.
