### ISSUE TITLE
Not working with kitty?

### ISSUE THREAD

**Issue by spamwax** [ojroques/vim-oscyank#14]
I can use this wonderful plugin with Alacritty but can't seem to get it to work with kitty.
This is my setting

```viml
let g:oscyank_term = 'kitty'
vnoremap <leader>c :OSCYank<CR>
```
It show a message like `[oscyank] 52 characters copied` but my clipboard it not updated.
I also tried yanking to `+` register and then using `OSCYankReg +`

kitty version is `kitty 0.22.2` and I am on macOS Catalina

*EDIT*
I just tested this with `kitty 0.22.0` on Linux and it worked. So it's either newer version of kitty that has issue or the combination of kitty+macOS

*EDIT 2*
Does not seem the issue is related to kitty versions as I tried all the versions of it back to `kitty 0.21.2`. So it seems it's a macOS+kitty problem.

Interestingly I found a change in kitty's implementation of OSC in `kitty 0.22.0` [change log](https://sw.kovidgoyal.net/kitty/changelog/#id3). Is that change of any interest to this project? Note that the reported issue here persists for versions before and after `0.22.0`

*EDIT 3*
Seems the issue was related to `clipboard_control` option of kitty. I was using `clipboard_control yes` (from older kitty versions?) but changing it to `clipboard_control write-clipboard write-primary` fixed the problem.

**Comment by ojroques** [comment]
I'm glad you managed to solve your issue. I'll remember your fix for future issues like this one :)
