### ISSUE TITLE
suggest how to OSCYank current line

### ISSUE THREAD

**Issue by jmegner** [ojroques/vim-oscyank#22]
Thanks so much for the wonderful plugin.  It took me a while to figure out how to OSCYank the current line, and I imagine a lot of other users have the same desire, so I was hoping you could add another example usage to help them

Just below...
>`<leader>oip  " copy the inner paragraph`

add...
>`<leader>o_ "copy the current line`

I've been using vim a while and I knew that normal-mode-underscore moved to the beginning of nonwhitespace of a line, but I didn't know it was the movement needed to do "apply the operation to the whole line".

**Comment by ojroques** [comment]
Good suggestion, I've updated the README
