### ISSUE TITLE
Change "autocmd TextYankPost" to support neovim Y in readme

### ISSUE THREAD

**Issue by Racle** [ojroques/vim-oscyank#27]
Change 
```
autocmd TextYankPost * if v:event.operator is 'y' && v:event.regname is '' | execute 'OSCYankReg "' | endif
```
to 

```
autocmd TextYankPost * if (v:event.operator is 'y' || v:event.operator is 'Y') && v:event.regname is '' | execute 'OSCYankReg "' | endif
```

to support neovim `Y` yank (same as `y$`).

This seems to be working fine on my neovim configuration.

**Comment by ojroques** [comment]
I've tried on Neovim and `Y` is supported even with the current autocommand. Can you provide more context about this change?

**Comment by Racle** [comment]
> I've tried on Neovim and `Y` is supported even with the current autocommand. Can you provide more context about this change?

I was 100% sure I didn't get yank with `Y` when I initially tested. I got stuff to my clipboard with `yy`.

But now after I reverted my change and tested again, it works as intended.

Don't know what changed, but it works just fine. I'll close this issue as it seems to be failure on my part.
