### ISSUE TITLE
Does Wezterm support OSC-52?

### ISSUE THREAD

**Issue by krishnakumarg1984** [ojroques/vim-oscyank#3]
I am using [wezterm](https://wezfurlong.org/wezterm) as my terminal emulator. Can you please comment on whether OSC-52 works on it?

**Comment by ojroques** [comment]
Hello!

A quick search returned nothing about OSC52 and wezterm. So the best way to know is to test yourself if the plugin works: connect via SSH to a machine, install the plugin and run Vim, try to copy some text and check if your clipboard has been updated.

Or you can open an issue directly on wezterm repo asking if they support it and if not, if they plan to do so. Hope that helped, feel free to re-open this issue if you have other questions.

**Comment by wez** [comment]
Yes, wezterm supports OSC 52 for setting the clipboard.  This is now (briefly) documented at https://wezfurlong.org/wezterm/escape-sequences.html#operating-system-command-sequences

**Comment by ojroques** [comment]
Great news! I've added wezterm to the terminal list.
