### ISSUE TITLE
Removing indentation?

### ISSUE THREAD

**Issue by djensenius** [ojroques/vim-oscyank#37]
I seem to be losing my indentation and a line break when copying a full line. Was there a change recently that caused this?

**Comment by ojroques** [comment]
Hello,

Yes the last commit refactored the code and the option to trim whitespaces is now the default. You can change that with:
```vim
let g:oscyank_trim = 0
```

**Comment by djensenius** [comment]
Thanks, just posting to this issue for visibility, here is how I have it set up using [lazy.nvim](https://github.com/folke/lazy.nvim):

https://github.com/djensenius/dotfiles/blob/7f6e928979c87578aabd86142efb00e296fffbcb/nvim/lua/plugins/oscyank.lua

**Comment by ojroques** [comment]
Thanks! Note that `vim.g.oscyank_term` is not used anymore so you can safely remove it.

**Comment by ojroques** [comment]
Note that the latest commit set the default trim option back to `false` as it seems to cause confusion.
