### ISSUE TITLE
Deprecation Warning instantly disappears

### ISSUE THREAD

**Issue by Swivelgames** [ojroques/vim-oscyank#38]
I had to yank multiple times in order to make sure that I had actually seen something, and then I went through the [diff](https://github.com/ojroques/vim-oscyank/commit/ffe827a27dae98aa826e2295336c650c9a434da0) in order to confirm that deprecation warnings had actually been added and to read what they said. Unfortunately I couldn't make out what the warning was because it only flashed on for a split second.

**Comment by ojroques** [comment]
I've removed the deprecation notices, it's been long enough.
