### ISSUE TITLE
OscYankRegister missing newlines on osx ventura

### ISSUE THREAD

**Issue by dmfay** [ojroques/vim-oscyank#40]
I just started noticing this after upgrading recently. Using a test file like this:

```
aaaa
bbbb
cccc
```

Without oscyank installed:

- yanking the aaaa line with `yy` and pressing `p` with the cursor on line bbbb pastes aaaa below bbbb as a full line;
- `aaaa\n` is stored in the `*`, `+`, and `"` registers

With oscyank:

- yanking aaaa and pressing `p` with the cursor on line bbbb pastes aaaa into or at the end of line bbbb depending on the cursor column, e.g. "bbaaaabb" or "bbbbaaaa";
- `aaaa` is stored in the `*` and `+` registers, `aaaa\n` in `"`

osx uses the `*`/`+` selection buffers to paste so the correct value in the `"` buffer is ignored. Pasting full lines works correctly in Linux where I don't have neovim using the selection buffers `*`/`+` (so only the `"` buffer is filled).)

Adding `execute OSCYankRegister *` after the yank to register `"` in my autocmd or even replacing the `"` with `*` doesn't change anything.

## configuration

```
augroup oscyank
  autocmd TextYankPost * if v:event.operator is 'y' && v:event.regname is '' | execute 'OSCYankRegister "' | endif
augroup end
```

## to reproduce

1. open neovim 0.8.0 or 0.8.3 on osx ventura
2. enter a few lines of text
3. `yy` to yank a line
4. `p` to paste, or otherwise view the register contents

**Comment by ojroques** [comment]
Weird. I use Linux so it's hard to reproduce on my side. But I don't see why the plugin would mess up with your registers since the autocommand only reads from the unnamed register '"'.

What are your value of options `clipboard` and `selection` in your config?

**Comment by dmfay** [comment]
> Weird. I use Linux so it's hard to reproduce on my side. But I don't see why the plugin would mess up with your registers since the autocommand only reads from the unnamed register '"'.
>
> What are your value of options `clipboard` and `selection` in your config?

`clipboard` is `unnamedplus`, and I don't set `selection` or `behave` so it's the default `inclusive`, all on both osx and linux.

I should've tried a different terminal emulator though -- everything's fine in Terminal.app so I think this is a [wezterm](https://wezfurlong.org/wezterm) issue. Thanks for the plugin! 👋

**Comment by j-hui** [comment]
I was able to reproduce this issue on macOS with Wezterm, Alacritty, and Kitty. 

Weirdly enough, Terminal.app is the only terminal (I use) that does not exhibit this issue. This issue is also absent in Vim.

The issue appears to be from 14685fcc4f487ca42dfe786dd54e4b2913370085; once I revert to the commit before that, the issue disappears.

**Comment by j-hui** [comment]
I think I found the culprit: the following change to oscyank.vim "fixes" the issue:

```diff
-  \ 'trim': get(g:, 'oscyank_trim', 1),
+  \ 'trim': get(g:, 'oscyank_trim', 0),
```

The newly introduced `trim` option is being read too early, and seems to ignore me setting the value `0` later on. I'm not sure why the evaluation order is different on different systems and on Neovim vs Vim, but that seems to be the root of the issue.

(Also, I have no idea why this _isn't_ causing issues for Terminal.app; maybe it's doing something sketchy?)

**Comment by ojroques** [comment]
The latest commit sets the default trim setting to `false`.
