### ISSUE TITLE
Question about tmux TERM 

### ISSUE THREAD

**Issue by ethagnawl** [ojroques/vim-oscyank#41]
Thanks for this versatile plugin! I can confirm that it's working great when sshing into my remote server and is a tremendous productivity booster.

Unfortunately, I'm getting hung up trying to use it in conjunction with tmux on the remote server. I _think_ my problem is that I'm unable to set `Ms` correctly via the various tmux configuration incantations. I've tried upgrading from 2.6 to 3.4-next and that didn't change anything. Something that I'm not entirely clear on, which is probably the problem, is that I'm not sure which machine's `$TERM` I should be using: my host or the server? I'm also not clear on whether tmux is expected to be running on the local machine or on the server in the linked documentation. (To be clear: I'm trying to ssh into a remote machine, run tmux on the remote machine and run vim inside the remote tmux session.)

Any pointers would be greatly appreciated!

**Comment by ojroques** [comment]
Hello, I'm glad you like the plugin.

To work with tmux, you need two things:
* Your terminal emulator must be compatible with OSC52 but that seems to be the case.
* On machine where you have your tmux instance running, so on the remote machine in your case, you need to put this in your tmux config: `set -s set-clipboard on` (and not `external`).

That should be all for the plugin to work.

**Comment by ethagnawl** [comment]
Thanks for the prompt response, @ojroques! 

I have tried adding both `set-clipboard on|external` to my tmux config without success. I'm going to try again with a simplified tmux config, though.

**Comment by ojroques** [comment]
Could you share your vim and tmux config on the remote server ? Also, what terminal emulator are you using ?

**Comment by ethagnawl** [comment]
I just rebuilt tmux next-3.4 and it's now working using: `set-option -s set-clipboard on`. I'm not sure what changed but I'll follow up if I can figure it out. 

Either way, thanks for your help and for such a useful utility!

**Comment by ethagnawl** [comment]
I did just uncover something strange. As mentioned, I built tmux myself and when I start it using $PATH `Ms` is not set; when I start it using the absolute path to the same binary, `Ms` does get set and this plugin works as expected. This is almost certainly not a vim-oscyank issue but I wanted to mention it in case anyone else runs into this particular problem.

**Comment by ojroques** [comment]
Good to know, thanks.
