### ISSUE TITLE
Add command that copies the provided argument

### ISSUE THREAD

**Issue by 3N4N** [ojroques/vim-oscyank#45]
A vim command `:OSCYankText` that copies all the arguments as a single string of text will be very useful.  It'll replace the use case of `let @* = "some text"`.

I realize that I can do `:call OSCYank("some text")`, and I personally am happy to do that, but the deprecation warning when executing `:OSCYank` might mean to someone that `OSCYank()` is dysfunctional.

**Comment by ojroques** [comment]
I've removed the deprecation notices, it's been long enough.
