### ISSUE TITLE
Not working when using Neovim in tmux

### ISSUE THREAD

**Issue by OracleMachine** [ojroques/vim-oscyank#46]
I followed the [instruction](https://github.com/tmux/tmux/wiki/Clipboard#quick-summary). But I still cannot yank text to clipboard if using neovim nested inside tmux.

If the neovim start with tmux. It works

**Comment by ojroques** [comment]
Did you set `set -s set-clipboard on` in your tmux config?

**Comment by jeremyjjbrown** [comment]
i have `set -s set-clipboard on` and it's not working for me in neovim.

 nvim -v
NVIM v0.9.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

  tmux -V
tmux 3.3a

LMK any other details to check.

**Comment by ojroques** [comment]
What is your terminal? Also, can you provide your Neovim config?

**Comment by jeremyjjbrown** [comment]
Alactritty. My Neovim config is quite large. Let me try with a minimal config and see if I can recreate.

**Comment by jeremyjjbrown** [comment]
I get the "[oscyank] N charactors copied" in the statusline wit :OSCYankVisual but nothing in my clipboard. Ctrl+Shift+c copies from tmux
```
  cat .config/tmux/tmux.conf
set -g set-clipboard on
```
```
  cat .config/nvim/init.lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
    vim.fn.system({
        "git",
        "clone",
        "--filter=blob:none",
        "https://github.com/folke/lazy.nvim.git",
        "--branch=stable", -- latest stable release
        lazypath,
    })
end
vim.opt.rtp:prepend(lazypath)

vim.g.mapleader = " " -- Make sure to set `mapleader` before lazy so your mappings are correct

require("lazy").setup({

    'ojroques/vim-oscyank',

})
```

**Comment by ojroques** [comment]
I did not manage to reproduce on Alacritty + tmux. But if you're using Neovim, I encourage you to check https://github.com/ojroques/nvim-osc52 instead.

**Comment by doomzhou** [comment]
this: [doc](https://github.com/tmux/tmux/wiki/Clipboard#quick-summary) not applicable.  
my env: iterm2 + tmux3.4 + vim(plugin installed)
first step: `set -g set-clipboard on`  not `set -s set-clipboard external
`

**Comment by zhuzhzh** [comment]
I use vim9 + tmux 3.4.  oscyank doesn't work.

```shell
% echo $TERM
gnome-256color
```

set -s set-clipboard external
tmux_conf_copy_to_os_clipboard=true
set -as terminal-features ',gnome-256color:Ms=\E]52;%p1%s;%p2%s\007'
set -s copy-command 'xsel -i'

**Comment by epheien** [comment]
Same issue, but it's fine with v1.0.0.
I'll look into the specific cause when I'm free.

**Comment by epheien** [comment]
after I `set-option -g set-clipboard on` in .tmux.conf, I works
