### ISSUE TITLE
Not compiling for arm-based processor

### ISSUE THREAD

**Issue by excited-bore** [ojroques/vim-oscyank#51]
When i install this on a raspberry pi, i get this error:
````
runtime/cgo
# runtime/cgo
gcc: error: unrecognized command-line option '-marm'
`````

I think it's related to setting the wrong [C-compiler](https://github.com/golang/go/issues/16801)

**Comment by ojroques** [comment]
I don't see how it could be related to the plugin. There's no need to compile anything with this plugin.

It may be an issue from Vim/Neovim.

**Comment by excited-bore** [comment]
Sorry, my bad. This meant for [Osc52](https://github.com/theimpostor/osc). 
I didn't realize i had the wrong tab open when opening an issue.
