### ISSUE TITLE
tmux / mosh combo doesn't work

### ISSUE THREAD

**Issue by normen** [ojroques/vim-oscyank#52]
When using tmux AND mosh it doesn't seem to work properly. The funny thing is it does work with either, just not with both together:

- `vim` + `tmux` + `mosh` = fail
- `vim` + `tmux` + `ssh` = win
- `vim` + `mosh` = win

**Comment by kkebo** [comment]
Are you using tmux 3.4? In my case, tmux 3.3 doesn't work, but tmux 3.4 works well.

**Comment by normen** [comment]
Hm, okay. Running on 3.3a on that machine.. Thanks.
