### ISSUE TITLE
Consider expanding the usage example(s)?

### ISSUE THREAD

**Issue by wez** [ojroques/vim-oscyank#6]
I'm not by any means a vimscript guru, so I found that I had to do relatively speaking a lot of reading and experimenting to achieve my goal which is:

* `yy` should copy the line to the clipboard
* `y` in visual mode should also copy to the clipboard

I couldn't find a way to conveniently express that in a one-liner, so I wound up with this:

```vim
function! WezPostYank(event)
  if a:event.operator is 'y'
    if a:event.visual
      OSCYank
    elseif a:event.regname is ''
      call YankOSC52(join(a:event.regcontents))
    endif
  endif
endfunction
autocmd TextYankPost * call WezPostYank(v:event)
```

Is there a better way to achieve this?
Would you consider expanding the readme to show something like this?

**Comment by fanzeyi** [comment]
```
nnoremap yy V:OSCYank<CR>
vnoremap y :OSCYank<CR>
```

:P

**Comment by wez** [comment]
@fanzeyi :-p but I also want it to do the normal yank stuff too :)

**Comment by ojroques** [comment]
Hello,

Does that work for you?
```
nnoremap yy yy:OSCYank "<CR>
vnoremap y :OSCYank<CR>
```

This one keeps the normal yank behavior. It also only affects `yy` in normal mode, not the entire `y` command.

Otherwise I think your function is equivalent to:
```
autocmd TextYankPost * if v:event.operator is 'y' && v:event.regname is '' | OSCYankReg " | endif
vnoremap y :OSCYank<CR>
```

(*ie* all your `y` operations in normal mode are copied to the clipboard)

**Comment by OrbitalHustler** [comment]
With only this

```
autocmd TextYankPost * if v:event.operator is 'y' && v:event.regname is '' | execute 'OSCYankReg "' | endif
```

All the `y` operations are copied to the clipboard. In my opinion it should be added to the README. I spent a while looking how to do this, until I found this issue.
